### ISSUE TITLE
Кнопка "Назад" не работает на экранах "Отчёты" и "Меню"

### ISSUE THREAD

**Issue by UHolder** [handydevcom/financier#1]
На экранах "Счета", "Журнал", "Бюджеты" поведение кнопки "Назад" правильное - выход из приложения.

На экранах "Отчёты" и "Меню" кнопка "Назад" вообще не работает, поведение кнопки на этих экранах должно быть как и на других экранах - выход из приложения (а в главном меню можно вместо выхода выполнять переход на предыдущий экран).

Xiaomi Redmi Note 4

**Comment by mbarashkov** [comment]
Исправлено в 2.0.9
