### ISSUE TITLE
Project building issues

### ISSUE THREAD

**Issue by sergentum** [handydevcom/financier#14]
Could you please remove all environment specific strings like "/Users/misha/Projects/InHouse/"
or "rootProject.file("./Keys/financier.properties")" which doesn't exist in repository?
Maybe clean up develop branch for other contributors, so it could be compiled without any issues and keep your personal settings related to release in master branch?
I'd like to participate in development but I can't build the project.
![2021-10-23 10_03_15-financier – build gradle IntelliJ IDEA](https://user-images.githubusercontent.com/4054762/138548375-0cdf16b4-b3da-4f73-9177-65f7b96674ba.png)
![2021-10-23 10_04_18-financier – java IntelliJ IDEA](https://user-images.githubusercontent.com/4054762/138548377-a57db612-f3d8-4446-afec-65c478ad209a.png)

**Comment by mbarashkov** [comment]
Done @sergentum
