### ISSUE TITLE
Account blotter : Zero balance for transfer

### ISSUE THREAD

**Issue by vov4uk** [handydevcom/financier#17]
STR : 
Open Accounts tab
Click on some Account and click Blotter button

How it looks now 
Account blotter 
![image](https://user-images.githubusercontent.com/2099449/140768076-7e0e78da-f1e9-4666-a2ce-22da593cfd57.png)
General blotter
![image](https://user-images.githubusercontent.com/2099449/140768141-3d3ef803-6168-409b-8df6-0d0e19c9b48b.png)

Version 2.0.11
![image](https://user-images.githubusercontent.com/2099449/140768206-346d92b0-88a9-4626-85de-96c792a5d0b2.png)

**Comment by mbarashkov** [comment]
Fixed on develop branch

**Comment by vov4uk** [comment]
Привіт @mbarashkov, а можна викотити ці зміни в новий реліз?
