### ISSUE TITLE
Cannot specify auto backup time

### ISSUE THREAD

**Issue by oleg-derevenetz** [handydevcom/financier#18]
In original Financisto app, there was a setting of auto backup time between "Turn on auto backup" and "Notify about auto backup issues". In Financier, I see no configuration item of such kind, despite the fact that I turned the auto backup on.

**Comment by oleg-derevenetz** [comment]
As I see, there is a corresponding entry in `preferences.xml` for F-Droid, but not for Google Play. Is this intentional?

**Comment by mbarashkov** [comment]
This feature wasn't ported correctly. Now it's fixed.
