### ISSUE TITLE
Empty Transactions / Templates crash

### ISSUE THREAD

**Issue by vov4uk** [handydevcom/financier#5]
Version 2.0.14
Edit button for transactions crash
Try to add template or edit previously added transaction  - app stop respond and crash

![image](https://user-images.githubusercontent.com/2099449/105832875-1d575b80-5fd1-11eb-974f-7be22d3cb3d9.png)
![image](https://user-images.githubusercontent.com/2099449/105832997-4841af80-5fd1-11eb-9eb8-240cccbb5dfd.png)

**Comment by mbarashkov** [comment]
This is fixed in 2.0.15
